<<<<<<< HEAD
# Generated by Django 2.1.5 on 2019-01-07 18:44
=======
# Generated by Django 2.1.4 on 2018-12-29 18:33
>>>>>>> fea2939af2a300b539ec842ee25e3e56c5950068

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Banks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbr', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
=======
>>>>>>> fea2939af2a300b539ec842ee25e3e56c5950068
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(auto_now=True)),
<<<<<<< HEAD
                ('bank_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='expenses.Banks')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
=======
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
>>>>>>> fea2939af2a300b539ec842ee25e3e56c5950068
            ],
        ),
    ]
