# Generated by Django 2.1.4 on 2019-01-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_auto_20190108_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='month',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='expenses',
            name='year',
            field=models.CharField(default='0', max_length=4),
        ),
    ]
